#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Myro Productions Website
# Spec: 001-myro-productions-personal-website

set -e

echo "========================================"
echo "Myro Productions Website - Dev Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check Node.js version
check_node() {
    echo -e "${BLUE}Checking Node.js version...${NC}"

    if ! command -v node &> /dev/null; then
        echo -e "${RED}Node.js is not installed. Please install Node.js v20.9+${NC}"
        exit 1
    fi

    NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
    if [ "$NODE_VERSION" -lt 20 ]; then
        echo -e "${RED}Node.js v20.9+ is required. Current version: $(node -v)${NC}"
        exit 1
    fi

    echo -e "${GREEN}Node.js version OK: $(node -v)${NC}"
}

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start within ${max}s${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# ============================================
# INITIALIZATION (Run once for new projects)
# ============================================

initialize_project() {
    echo ""
    echo -e "${YELLOW}=== PROJECT INITIALIZATION ===${NC}"

    # Check if project is already initialized
    if [ -f "package.json" ]; then
        echo -e "${GREEN}Project already initialized (package.json exists)${NC}"
        return 0
    fi

    echo -e "${BLUE}Initializing Next.js 15 project...${NC}"

    # Initialize Next.js project
    npx create-next-app@latest . --typescript --eslint --app --tailwind --yes

    # Install additional dependencies
    echo -e "${BLUE}Installing animation libraries...${NC}"
    npm install motion gsap @gsap/react

    echo -e "${GREEN}Project initialized successfully!${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

install_deps() {
    echo ""
    echo -e "${YELLOW}=== INSTALLING DEPENDENCIES ===${NC}"

    if [ ! -f "package.json" ]; then
        echo -e "${RED}No package.json found. Run initialization first.${NC}"
        exit 1
    fi

    npm install
    echo -e "${GREEN}Dependencies installed${NC}"
}

# ============================================
# START DEVELOPMENT SERVER
# ============================================

start_dev() {
    echo ""
    echo -e "${YELLOW}=== STARTING DEVELOPMENT SERVER ===${NC}"

    # Kill any existing process on port 3000
    if command -v lsof &> /dev/null; then
        lsof -ti:3000 | xargs kill -9 2>/dev/null || true
    fi

    echo -e "${BLUE}Starting Next.js dev server...${NC}"
    npm run dev &

    wait_for_service 3000 "Next.js Frontend"
}

# ============================================
# MAIN EXECUTION
# ============================================

main() {
    check_node

    case "${1:-start}" in
        init)
            initialize_project
            install_deps
            ;;
        install)
            install_deps
            ;;
        start)
            install_deps
            start_dev
            ;;
        dev)
            start_dev
            ;;
        *)
            echo "Usage: $0 {init|install|start|dev}"
            echo ""
            echo "Commands:"
            echo "  init    - Initialize new project (run once)"
            echo "  install - Install dependencies only"
            echo "  start   - Install deps and start dev server"
            echo "  dev     - Start dev server only"
            exit 1
            ;;
    esac

    echo ""
    echo "========================================"
    echo -e "${GREEN}Environment Ready!${NC}"
    echo "========================================"
    echo ""
    echo "Services:"
    echo "  Frontend: http://localhost:3000"
    echo ""
    echo "Quick commands:"
    echo "  npm run dev    - Start development server"
    echo "  npm run build  - Build for production"
    echo "  npm run lint   - Run ESLint"
    echo ""
}

main "$@"
